Vagrant.configure("2") do |config|
 config.vm.define :balanceador do |balanceador|
   balanceador.vm.box = "bento/ubuntu-20.04"
   balanceador.vm.network :private_network, ip: "192.168.100.7"
   balanceador.vm.hostname = "balanceador"
   balanceador.vm.provision "shell", path: "script2.sh"
end
 config.vm.define :web1 do |web1|
   web1.vm.box = "bento/ubuntu-20.04"
   web1.vm.network :private_network, ip: "192.168.100.8"
   web1.vm.hostname = "web1"
   web1.vm.provision "shell", path: "script.sh"
 end
config.vm.define :web2 do |web2|
   web2.vm.box = "bento/ubuntu-20.04"
   web2.vm.network :private_network, ip: "192.168.100.9"
   web2.vm.hostname = "web2"
   web2.vm.provision "shell", path: "script3.sh"
 end
end